---
title: "Python Project: Education Completion Rates Across Countries"
format: gfm
---

## The Prompt

How do global school attendance rates differ by gender, and what patterns emerge across regions and levels of development?

## Supproting Questions

Does the direction of the gender gap differ across regions?

How does South Africa compare with the broader regional trend?

How does gender parity change with a country's level of development?

Is South Africa unique, or does it reflect the broader attendance patterns and gender disparities observed across other less developed countries?

## Setup
## Import environments

For Exploration/ Claculations
```{python}
import pandas as pd
import statsmodels.api as sm
```

For Graphs
```{python}
import seaborn as sns
import matplotlib.pyplot as plt
```

## In Terminal

pip3 install openpyxl
This allows the excel file to be read. 

## Importing in the Data

```{python}
file_path = '~/Library/Mobile Documents/com~apple~CloudDocs/MSBAAcademics/Python/PotentialDataSets/CompletionRateData.xlsx'
```

```{python}
unicef_data_primary = pd.read_excel(file_path, sheet_name='Primary')

unicef_data_lower = pd.read_excel(file_path, sheet_name='Lower secondary')

unicef_data_upper =pd.read_excel(file_path, sheet_name='Upper secondary')
```
(Imported as seperate Data Frames)

## Initial Exploration

Look at the first & last 5 rows of each sheet, & shape
```{python}
unicef_data_primary.head()
unicef_data_primary.tail()
unicef_data_primary.shape
```

```{python}

unicef_data_lower.head()
unicef_data_lower.tail()
unicef_data_lower.shape
```

```{python}
unicef_data_upper.head()
unicef_data_upper.tail()
unicef_data_upper.shape
```

## Concatenate the 3 data frames into 1 data frame (df)

First add an Education Level Column called Level
```{python}
unicef_data_primary['Level'] = 'Primary'
unicef_data_lower['Level'] = 'Lower secondary'
unicef_data_upper['Level'] = 'Upper secondary'
```

Concatnate all 3 data frames/ sheets
```{python}
unicef_all = pd.concat([
    unicef_data_primary,
    unicef_data_lower,
    unicef_data_upper
])
```

## Cleaning the Data
## Renaming

View Column names
```{python}
unicef_all.columns
```

Create a funtion to rename the columns, & save the changes
```{python}
def rename_columns(df):
    df = df.rename(columns = {'ISO3': 'Country Abbreviation',
        'Total': 'Total Attendance (%)',
        'Gender_Female': 'Female Attendance (%)',
        'Gender_Male': 'Male Attendance (%)',
        'Residence_Rural': 'Rural Attendance (%)',
        'Residence_Urban': 'Urban Attendance (%)',
        'WealthQuintile_Poorest': 'Poorest Quintile Attendance (%)',
        'WealthQuintile_Second': 'Second Quintile Attendance (%)',
        'WealthQuintile_Middle': 'Middle Quintile Attendance (%)',
        'WealthQuintile_Fourth': 'Fourth Quintile Attendance (%)',
        'WealthQuintile_Richest': 'Richest Quintile Attendance (%)'
        })
    return df
# the 'df =' means the new names will replace the old ones
```

Run the function
```{python}
unicef_all = rename_columns(unicef_all)
```

## Clarity on Column content/ Dictionaries

Dictionary for region names
```{python}
unicef_all["Region"].unique()
```

Dictionary for region names
```{python}
region_names = {'SA': 'South Asia',
    'ECA': 'Europe & Central Asia',
    'MENA': 'Middle East & North Africa',
    'SSA': 'Sub-Saharan Africa',
    'LAC': 'Latin America & the Caribbean',
    'EAP': 'East Asia & the Pacific'
}
```

Option to Apply Dictionary:
Instead of Applying Dictionaries you can also use get() with your result if you need more than the abbreviation.
```{python}
unicef_all['Region'] = unicef_all['Region'].map(region_names)
```

Dictionary for sub-region names
```{python}
unicef_all["Sub-region"].unique()
```

```{python}
subregion_names = {'SA': 'South Asia',
    'EECA': 'Eastern Europe & Central Asia',
    'MENA': 'Middle East & North Africa',
    'WE': 'Western Europe',
    'ESA': 'Eastern & Southern Africa',
    'LAC': 'Latin America & the Caribbean',
    'EAP': 'East Asia & the Pacific',
    'WCA': 'West & Central Africa'
}
```

Option to Apply Dictionary:
Instead of Applying Dictionaries you can also use get() with your result if you need more than the abbreviation.
```{python}
unicef_all['Sub-region'] = unicef_all['Sub-region'].map(subregion_names)
```

## Remove unnamed columns
```{python}
unicef_all.columns

unicef_all = unicef_all.drop(columns = [ 
    'Unnamed: 18', 
    'Unnamed: 19', 
    'Unnamed: 20',
    'Unnamed: 21', 
    'Unnamed: 22'
])
```

## Exploration of unicef_all
```{python}
unicef_all
```

First 5 rows
```{python}
unicef_all.head()
```

Last 5 rows: The last few rows are summaries
```{python}
unicef_all.tail()
```

```{python}
unicef_all.info()
```

## Convert Data types of object to float64

Function for type change
```{python}
def type_change(df, column_name):
    df[column_name] = pd.to_numeric(df[column_name], errors="coerce")
```

For loop: all object columns 
```{python}
attendance_columns = [
    'Total Attendance (%)',
    'Female Attendance (%)',
    'Male Attendance (%)',
    'Rural Attendance (%)',
    'Urban Attendance (%)',
    'Poorest Quintile Attendance (%)',
    'Second Quintile Attendance (%)',
    'Middle Quintile Attendance (%)',
    'Fourth Quintile Attendance (%)',
    'Richest Quintile Attendance (%)'
]

for i in attendance_columns:
    type_change(unicef_all, i)
```

Check if it changed the objects to floats
```{python}
unicef_all.info()
```

```{python}
unicef_all.sort_values('Total Attendance (%)', ascending = True)
```

This data contains summary rows
For summary rows: Country Abbreviation = NaN
## Filter out summary rows
```{python}
unicef_all = unicef_all[unicef_all['Country Abbreviation'].notna()]
```

## Calculations
Start with calculations now that the types are adjusted:
## Create Gender Gap column 

```{python}
unicef_all['Gender Attendance Gap (F-M)'] = (
    unicef_all['Female Attendance (%)'] - unicef_all['Male Attendance (%)'])
```

Positive values mean female attendance is higher than male attendance in that row -> negative values mean male attendance is higher.

```{python}
unicef_all[['Country', 'Region', 
            'Sub-region', 'Development Regions', 
            'Level', 'Total Attendance (%)', 
            'Female Attendance (%)', 'Male Attendance (%)',
            'Gender Attendance Gap (F-M)']].sort_values('Gender Attendance Gap (F-M)', ascending=False)
```

```{python}
unicef_all
```

## Plot
## Does the direction of the gender gap differ across regions?

```{python}
gap_mean = (unicef_all
            .groupby('Region')['Gender Attendance Gap (F-M)']
            .mean()
            .sort_values())
```

```{python}
plt.figure()

gap_mean.plot(kind = 'barh')

plt.xlabel('Average Gender Attendance Gap (Female % - Male %)')
plt.ylabel('Region')
plt.title('Average Gender Attendance Gap by Region')

plt.show()
plt.close()
```

For East Asia & the Pacific, Latin America & the Caribbean, and the Middle East & North Africa, the gender gap is positive. This indicates that girls have higher school attendance rates than boys. For Europe & Central Asia shows little difference between male and female attendance. In contrast, Sub-Saharan Africa and South Asia display negative gender gaps. This means boys attend school at higher rates than girls. 

## How does South Africa compare with the broader regional trend?
```{python}
south_africa = unicef_all[unicef_all['Country'] == 'South Africa']
```

```{python}
south_africa
```

South Africa's region is Sub-Saharan Africa. A histogram will be useful to understand how its gender gap compares with the overall distribution of countries in this region.

```{python}
region_group = unicef_all[unicef_all['Region'] == 'Sub-Saharan Africa']
```

```{python}
south_africa_combined = south_africa['Gender Attendance Gap (F-M)'].mean()
```

```{python}
combined_gap_region = (region_group.groupby('Country')['Gender Attendance Gap (F-M)'].mean())
```

Pick bin size for the histogram.
```{python}
region_group['Country'].nunique()
```

```{python}
plt.figure()

plt.hist(combined_gap_region, bins=5, color='grey', alpha=0.5)
plt.axvline(south_africa_combined, color='orange', label='South Africa (average across Education levels)')
plt.axvline(combined_gap_region.mean(), color='blue', label='Sub-Saharan Africa group mean')

plt.xlabel('Average Gender Attendance Gap (Female % - Male %)')
plt.ylabel('Number of Countries')
plt.title('Distribution of Gender Gap: Sub-Saharan Africa Countries (Combined Education Levels)')
plt.legend()

plt.show()
plt.close()
```

```{python}
print(f'The mean of the Sub-Saharan Africa Countries is {round(combined_gap_region.mean(), 2)}.')
```

```{python}
print(f'The mean of South Africa is {round(south_africa_combined, 2)}.')
```

The Sub-Saharan Africa regional mean is -1.8, indicating that, on average, boys have slightly higher attendance rates than girls across the region. South Africa’s stands in contrast to it's regional mean with an average gender gap of 5.42. South Africa is positioned far above the regional average and beyond the main concentration of countries in the distribution. While most Sub-Saharan African countries show a small gap favoring boys, South Africa demonstrates a comparatively larger gap favoring girls.

## How does gender parity change with a country's level of development?

```{python}
gap_by_development = (unicef_all
                    .groupby('Development Regions')['Gender Attendance Gap (F-M)']
                    .mean()
                    .sort_values())
```

```{python}
plt.figure()

gap_by_development.plot(kind='barh')

plt.xlabel('Average Gender Attendance Gap (Female % - Male %)')
plt.ylabel('Development Level of Region')
plt.title('Average Gender Attendance Gap by Development Level')

plt.show()
plt.close()
```

Order & Show this in a line graph
Order the development levels from least to most developed for a meaningful line trend
```{python}
plt.figure()

gap_by_development_ordered = gap_by_development.reindex([
    'Least Developed', 
    'Less Developed', 
    'Not Classified', 
    'More Developed'])

gap_by_development_ordered.plot(kind='line', marker='o')

plt.xlabel('Development Level of Region')
plt.ylabel('Average Gender Attendance Gap (Female % - Male %)')
plt.title('Average Gender Attendance Gap by Development Level')

plt.show()
plt.close()
```

Gender gaps in attendance across development level do not follow a simple linear relationship. Less Developed regions actually show the largest gap favoring girls, while More Developed regions show a smaller but still positive gap. However, Least Developed regions differ from this trend, displaying the only negative gap in the chart, indicating that boys attend school at higher rates than girls in the poorest countries.

## Is South Africa unique, or does it reflect the broader attendance patterns and gender disparities observed across other less developed countries?
## South Africa's Data

```{python}
south_africa = unicef_all[unicef_all['Country'] == 'South Africa']
```

```{python}
south_africa
```

## South Africa compared to other less developed countries

South Africa is classified as Less Developed. A histogram will be useful to understand how its gender gap compares with the overall distribution of countries in this group.

```{python}
less_developed = unicef_all[unicef_all['Development Regions'] == 'Less Developed']
```

```{python}
combined_gap = (less_developed.groupby('Country')['Gender Attendance Gap (F-M)']
    .mean())
```

```{python}
south_africa_combined = south_africa['Gender Attendance Gap (F-M)'].mean()
```

Pick bin size for the histogram.
```{python}
less_developed['Country'].nunique()
```

```{python}
plt.figure()

plt.hist(combined_gap, bins = 10, color = 'grey', alpha = 0.5)
plt.axvline(south_africa_combined, color = 'orange', label = 'South Africa (Average Across Education Levels)')
plt.axvline(combined_gap.mean(), color = 'blue', label = 'Less Developed Group Mean')

plt.xlabel('Average Gender Attendance Gap (Female % - Male %)')
plt.ylabel('Number of Countries')
plt.title('Distribution of Gender Gap: "Less Developed" Countries (Combined Education Levels)')
plt.legend()

plt.show()
plt.close()
```

```{python}
print(f'The mean of Less Developed Countries is {round(combined_gap.mean(), 2)}.')
```

```{python}
print(f'The mean of South Africa is {round(south_africa_combined.mean(), 2)}.')
```

The distribution of average gender gaps among Less Developed countries is 3.12. This indicates that the typical country in this category has girls’ attendance rates about 3% higher than the attendance of boys. South Africa’s mean (red line) appears further to the right, with an average gender gap of 5.42. This suggest that South Africa has a larger gap (favoring girls) compared to the typical country in the same category.

## Other Considerations
## Attendace Rates in War-Affected Areas

Save a list of the countries & the date of their data to a csv
```{python}
unicef_all[['Country', 'Time period']].drop_duplicates().sort_values('Country').to_csv('country_time_period.csv', index=False)
```

This file was imported to Gemini and generated a list of: Countries experiencing active war/armed conflict during the years specifically listed. 

```{python}
war_affected_countries = ['Afghanistan',
                        'Central African Republic',
                        'Colombia',
                        'Democratic Republic of the Congo',
                        'Iraq',
                        'Mali',
                        'Myanmar',
                        'Nigeria',
                        'Pakistan',
                        'South Sudan',
                        'State of Palestine',
                        'Sudan',
                        'Yemen']
```

```{python}
war_affected = unicef_all[unicef_all['Country'].isin(war_affected_countries)]
```

```{python}
war_gap = (war_affected.groupby('Country')['Gender Attendance Gap (F-M)'].mean().sort_values())
```

```{python}
plt.figure()

war_gap.plot(kind = 'barh', color = 'orange')

plt.xlabel('Average Gender Attendance Gap (F - M)')
plt.ylabel('Country')
plt.title('Average Gender Attendance Gap in War-Affected Countries')

plt.show()
plt.close()
```